app:
  name: Control Plane
  version: 1.0.0


spring:
  profiles:
    active: dev
  # Springboot2.6以后将SpringMVC 默认路径匹配策略从AntPathMatcher 更改为PathPatternParser，导致出错
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 5120MB
      max-request-size: 5120MB

# 应用服务 WEB 访问端口
server:
  port: 8809
#  servlet:
#    encoding:
#      charset: UTF-8
#      force-response: true # 修改 SpringBoot 默认响应为 utf-8 (原: charset=iso-8859-1)

swagger:
  enabled: true


# feign配置
feign:
  client:
    config:
      default: # default全局的配置
        loggerLevel: BASIC # 日志级别，BASIC就是基本的请求和响应信息
        connectTimeout: 5000 # 连接超时时间
  httpclient:
    enabled: true # 开启feign对HttpClient的支持
    max-connections: 200 # 最大的连接数
    max-connections-per-route: 50 # 每个路径的最大连接数

# 门户地址
portalUrl: http://localhost:7777
#portalUrl: https://geomodeling.njnu.edu.cn

# 节点端口
nodePort: 8060

# 容器引擎端口
enginePort: 8808

# 任务服务器
taskServerUrl: http://172.21.213.105:8061
#  taskServerUrl: http://localhost:8061

# 模型容器最低版本
msMinVersion: 0.4.1


